### ISSUE TITLE
"Like" a review on Fasttech doesn't work

### ISSUE THREAD

**Issue by brakenow** [pyllyukko/user.js#451] opened 2019-03-15 22:02 UTC
The code is `'<a id="content_Reviews_Helpful_1" href="javascript:__doPostBack('ctl00$content$Reviews$ctl03$Helpful','')">Yes</a>'`

Nothing happens when I click on 'yes'.

**Comment by pyllyukko** [comment] 2019-04-06 15:20
Console says `TypeError: postBackElement is undefined`. No idea what that means.

**Comment by nodiscc** [comment] 2023-07-05 22:52
Unable to reproduce, as the mentioned website does not exist anymore (https://duckduckgo.com/?q=Fasttech+closing&t=ftsa&ia=web)

Might have been a website bug, nothing indicates that this is related to user.js.

I suggest closing this issue.

**Closed** 2023-07-08 09:35 UTC
Labels: website breakage
