### ISSUE TITLE
Problems with privacy.resistFingerprinting

### ISSUE THREAD

**Issue by alabrand** [pyllyukko/user.js#186] opened 2016-10-03 22:15 UTC
I have tested this on clean installs of both Nightly 52 and Developer Edition 51.

Having user_pref("privacy.resistFingerprinting",            true); causes some dropdown menus to not function properly. What should happen is that you click once on the dropdown menu and it expands. But with privacy.resistFingerprinting set to true some dropdown menus appear and quickly dissapear. A workaround is that you have to hold your mouse button instead of clicking it, this will allow you to use the dropdown menus. But this is not a permanent solution. The most notable example is on nyaa. It should display the problems I've described.

I suggest removing this preference from the user.js.

**Comment by fmarier** [comment] 2016-10-03 23:03
Which "nyaa" are you referring to? Could you please post an example URL?

**Comment by alabrand** [comment] 2016-10-03 23:07
https://www.nyaa.se/

There's two dropdown menus at the top that should show the problem.

**Comment by fmarier** [comment] 2016-10-03 23:22
That looks like a bug in Firefox because that problem occurs whether or not JavaScript is enabled.

I'm not sure which of [these uses of the pref](http://searchfox.org/mozilla-central/search?q=resistFingerprinting&case=false&regexp=false&path=) is causing the problem though so I can't file a useful bug.

**Comment by alabrand** [comment] 2016-10-03 23:51
Yeah sounds like a weird issue.

**Comment by Atavic** [comment] 2016-10-04 01:25
The problem is in the site source. Browsers offer thousands of dropdown menu every second on the net with no issues. So, should a preference be discarded for a single, broken site?

Just copy the top links you're interested to and go directly to the index pages, as the dropdown menu offers standard links.

**Comment by Roman-Nopantski** [comment] 2017-01-20 15:24
Not sure if OP was using e10s: but this ticket https://bugzilla.mozilla.org/show_bug.cgi?id=1320801 has been resolved and will land in FF53, maybe FF52. We can probably close this issue. I had several ghacks regulars with the same problem - they even narrowed it down to e10s + resistFingerprinting.

**Comment by pyllyukko** [comment] 2017-01-20 21:50
Thanks for the info!

**Closed by pyllyukko** 2017-01-20 21:50 UTC
Labels: fingerprinting
