### ISSUE TITLE
Firefox connections on about:blank page

### ISSUE THREAD

**Issue by Gibbio** [pyllyukko/user.js#20] opened 2015-06-24 12:48 UTC
Hi, just installed user.js and I've noticed that when I start Firefox (about:blank is my start page) he make some connections:
netstat -nputw|grep firefox
tcp        0      0 xxx.xxx.xxx.xxx:33848     216.58.208.206:443      ESTABLISHED 13427/firefox
tcp        0      0 xxx.xxx.xxx.xxx:49776     216.58.208.206:80       ESTABLISHED 13427/firefox
tcp        0      0 xxx.xxx.xxx.xxx:42962     93.184.220.29:80        ESTABLISHED 13427/firefox
tcp        0      0 xxx.xxx.xxx.xxx:41561     52.25.32.149:443        ESTABLISHED 13427/firefox
tcp        0      0 xxx.xxx.xxx.xxx:33846     216.58.208.206:443      ESTABLISHED 13427/firefox
tcp        0      0 xxx.xxx.xxx.xxx:36906     68.232.34.191:443       ESTABLISHED 14420/firefox

There is any way in user.js to disable this automatic connections?
Thanks!

PS. OS: Fedora 22 x64, Firefox 38.0.5, no add-ons loaded

**Comment by pyllyukko** [comment] 2015-06-24 16:04
Hi.

Probably it is possible to disable these automatic connections.

Are you able to provide more information about these connections? For instance by observing the network traffic with tcpdump or [Wireshark](https://wireshark.org/) or some other tool. The connections going to port 80 should be clearly visible in the traffic capture and for the HTTPS connections (port 443), the DNS lookups would help. Also, an intercepting proxy tool, such as [Burp](http://portswigger.net/burp/) can be put in between your browser and the internet to observe what's happening.

Currently, there are some automatic connections that are allowed on purpose. Namely [browser.safebrowsing.malware.enabled](http://kb.mozillazine.org/Browser.safebrowsing.malware.enabled) and the [plugins.update.notifyUser](https://wiki.mozilla.org/Firefox3.6/Plugin_Update_Awareness_Security_Review) setting that opens the [Mozilla plugin check](https://www.mozilla.org/en-US/plugincheck/) page.

When I set the ```plugins.update.notifyUser``` to ```false```, I can only see a connection to ```aus4.mozilla.org``` that is related to the H.264 plugin (should be disabled with ```media.gmp-gmpopenh264.enabled```, I'll look into it).

I pushed a commit (65375871f42783a408365ad3d01416feecf9d72d), that sets ```browser.aboutHomeSnippets.updateUrl``` to ```""```... if you can check if that helped at all?

**Comment by Gibbio** [comment] 2015-06-25 10:23
tested with new version, got 2 connection:
93.184.220.29
54.230.185.55

here the captures:
http://www.armtc.net/54.230.185.55.pcap
http://www.armtc.net/93.184.220.29.pcap

**Comment by Gibbio** [comment] 2015-06-25 10:34
More captures here:
http://www.armtc.net/52.25.32.149.pcap
http://www.armtc.net/216.58.208.206.pcap
http://www.armtc.net/173.194.65.93.pcap

checked and all plugins/addons are disabled

**Comment by pyllyukko** [comment] 2015-06-25 19:30
Also forgot to mention about ```extensions.update.enabled``` (I probably need to document these in the README). I disabled the search engine update with c9f0ec441e82048cf78e892c975f580ea8e47bf5, as it really doesn't seem that relevant anyway.

> tested with new version, got 2 connection:
> 93.184.220.29
> 54.230.185.55

I checked the pcaps and:
* 93.184.220.29 seems to be an [OCSP](https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol) request (this is intended)
* 54.230.185.55 seems to be a request to ```self-repair.mozilla.org``` which seems to be yet another new Firefox feature (sigh!) called [self-heal](http://www.ghacks.net/2015/03/11/firefox-to-get-self-heal-feature/).

I wasn't able to find any setting related to that with a quick glance, but I'll keep looking, as it certainly sounds like something we want to disable. Thanks for reporting this!

**Comment by pyllyukko** [comment] 2015-06-25 19:43
Wait, no... It might be the [Heartbeat](https://wiki.mozilla.org/Advocacy/heartbeat) thingie, as the default value of ```browser.selfsupport.url``` is ```https://self-repair.mozilla.org/%LOCALE%/repair```, but that should've been taken care of with ca2c759c801c7d691073fadf7d488e37006acaaa. Hmm.

**Comment by Gibbio** [comment] 2015-06-26 07:22
Can you replicate this behavior in your environment? Maybe is just a Fedora OS customizations...
I've just created a little bash script with a netstat:
while true ; do
sleep 0.1
netstat -nputw|grep firefox
done
run script and then run firefox, wait a few seconds then connections start.

If you need more help/test ill help you!

**Comment by pyllyukko** [comment] 2015-06-26 08:00
> Can you replicate this behavior in your environment?

No. I'm not able to reproduce this, but I'll keep looking and I'm sure we'll figure it out. Can you double check the value of ```browser.selfsupport.url```?

**Comment by Gibbio** [comment] 2015-06-26 09:14
I've made this test:
fresh install of Xubuntu 15.04 i386 (virt-manager vm)
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install git
reboot

start firefox, disabled all the plugins/addons and changed default page to about:blank
git clone https://github.com/pyllyukko/user.js
cp user.js/user.js .mozilla/firefox/38hc8da2.default/
start firefox, check about:config for browser.selfsupport.url -> is empty
close firefox, start loop script with netstat as root then start firefox. After few seconds I can see firefox quering dns and then he connection to:
52.25.32.149:443
216.58.208.206:443
93.184.220.29:80

**Comment by nodiscc** [comment] 2015-06-26 10:16
Will try to reproduce this on Iceweasel (Debian) in the coming days.

**Comment by pyllyukko** [comment] 2015-06-27 21:40
Thanks, @nodiscc. I'll keep trying to reproduce this also.

**Comment by CHEF-KOCH** [comment] 2015-06-28 18:37
Capturing these connections is wasting time, that would only reveal what these connections are but not from what they are coming from. The easiest method is to search for all url stuff under about:config and compare them with uBlock/uMatrix dashboard (which loggs all requests).

```
app.helpdoc.baseURI
app.learn.more.baseURI
app.update.url
app.update.url.details
app.update.url.manual
browser.trackingprotection.gethashURL
browser.trackingprotection.updateURL
extensions.blocklist.detailsURL
extensions.blocklist.itemURL
extensions.blocklist.url
extensions.greasemonkey.stats.url; example - here greasmonkey some other extensions also collect data
extensions.https_everywhere._observatory.server_host; observatory.eff.org checks a lot in the background it's coming from https everywhere to check certs and submit them - ensure nothing like this is running ! also ensure sync is disabled !
extensions.update.background.url
and others, as said just search for the url's and uri's + disable the services
```

**Comment by pyllyukko** [comment] 2015-07-04 13:41
Looks like I've managed to implement few bugs with 65375871f42783a408365ad3d01416feecf9d72d and c9f0ec441e82048cf78e892c975f580ea8e47bf5 :( They should be fixed now with b213091306c4d4210b86377be65a9eaa64ddfa03.

@Gibbio, can you try again now?

**Comment by Gibbio** [comment] 2015-07-13 09:24
Sorry for the late reply, i've tested today with latest user.js version but i'm keep getting those connections. Seem that Firefox is getting worst every release :(

**Comment by pyllyukko** [comment] 2015-07-13 10:38
> Sorry for the late reply, i've tested today with latest user.js version but i'm keep getting those connections. Seem that Firefox is getting worst every release :(

We'll just have to keep trying then...

**Comment by Hunter-Github** [comment] 2015-08-14 04:14
Any progress on finding out the culprit? Is PaleMoon better in this regard?

**Comment by CHEF-KOCH** [comment] 2015-08-14 13:23
I already posted in another thread my ultimate pref that doesn't connect to anything except to loopback at startup (this is normal). Fennec and other pseudo secure Browsers are more or less placebo and can never beat the normal Firefox, since such projects are more of less hobby projects. Behind Mozilla they are a lot of more people and more eyes, so I'm really skeptical that they are more secure, expect since there is no proof. Mostly they using FF as the engine modding there stuff that's it, that can mostly be done by tweaking the prefs (as we did), except some other things like the engine (Pale Moon) and other unrelated things. Personally I would prefer projects that are under the microscope, like FF/ESR.

Also remember that some connections are made for update checks, downloading fonts/canvas, whatever this is not often easily to detect, so I recommend to disable/remove all installed plugins and extension (or use a clean installation [profile]) use uBlock/uMatrix + tcpdump/tcpview, normally that is enough to identify everything, no need Wireshark if you just want to make ensure that nothing goes in/out that you don't want. 

* Install an fresh Firefox without anything just out-of-the-box (do not start it yet!)
* Ensure you use our prefs.js and create a profile with this in it
* Download uMatrix/uBlock and start FF the first time, install and restart FF (just in case)
* Opern the dashboard from uBlock/uMatrix whish can reveal all connections, even from plugins (needs advanced option enabled)
* Install your addons one by one and check against TCPView/dump + uBlock/uMatrix each connection
* Ensure safebrowsing was disabled (enabled in our config)

If all goes wrong try my mentioned config and see if that helps, I do not have any connection (but of course it breaks hello chat and other things -> so what?!).

**Comment by Hunter-Github** [comment] 2015-08-15 19:11
@CHEF-KOCH : Okay will experiment as time allows, thanks.

**Comment by CHEF-KOCH** [comment] 2015-08-15 21:53
Imho most of the _hidden_ connections are from plugins and addons, thanks to the uMatrix/uBlock dev that he developed this awesome addon, that shows the most important stuff here without need to use any debug/dev tools (I mostly quick check against tcpview or something like this to capture the stuff that is made during the uBlock dashboard are loaded 2sec.).

Another notice:
Some addons e.g. Greasemonkey and others also wants to connect even if the _hidden_ option to send feedback are disabled within the GUI and/or about:config (w4.hackxxxyy + other connections - strange domain names btw!). Similar connection are also made from [HTTPS-Everywehere](https://github.com/EFForg/https-everywhere/issues/2428) and other popular addons, this is an result of _unlimited bandwidth_ and ignorant people that doesn't care anymore about metadata. For me this is a no-go and shows again you need to audit everything yourself, sad but true. 

I hope that may helps other people to reveal hidden _checks_.

**Comment by pyllyukko** [comment] 2015-11-05 11:02
@Gibbio: Can you check if ```about:networking``` reveals anything?

**Comment by berrythesoftwarecodeprogrammar** [comment] 2015-11-05 13:41
```
close firefox, start loop script with netstat as root then start firefox. After few seconds I can see firefox quering dns and then he connect to:
52.25.32.149:443
216.58.208.206:443
93.184.220.29:80
```
second ip is google
third is a digicert ocsp server
first no idea, but its not an ocsp server

**Comment by CHEF-KOCH** [comment] 2015-11-05 13:47
First is from [amazon](http://www.tcpiputils.com/browse/ip-address/52.25.32.149). 

So nothing to worry about.

**Comment by berrythesoftwarecodeprogrammar** [comment] 2015-11-05 13:48
why would it be nothing to worry about? its an amazon ec2 instance. anybody could own it

**Comment by CHEF-KOCH** [comment] 2015-11-05 14:02
Amazon [provides huge cdn](https://aws.amazon.com/cloudfront/) network which provides there own encryption and according to tcpipoutils it's clean. So this is coming from an addon which uploads/downloads stuff into the cloud or a page. We are not here to talk about each connection firefox makes if you not know to handle such things you must remove every addon, read the already given links and start step by step to see which is causing this. Even HTTPS/Firefox cosnatntly uploading stuff to analyze the certificates so you con complain about if or if you really not want it disable it via about:config.

**Comment by berrythesoftwarecodeprogrammar** [comment] 2015-11-05 14:04
this user has all addons disabled and is concerned about automatic connections so it would be nice to find out what all of the connections are for. im sure they are harmless but doesnt mean they are wanted

**Comment by CHEF-KOCH** [comment] 2015-11-05 14:06
Yes and if he doesn't want it, he can use our (already given) guides to handle it. Amazon can't be blocked like Google it will anyway ruine a lot of pages and encryption so even if you not like it you can't block it anyway. So what's the deal? 

I think we can close it and mark it as solved. If there are additional problems/question it better should go directly to FF and not over here because we can' fix hardcoded things even if we want it.

**Comment by berrythesoftwarecodeprogrammar** [comment] 2015-11-05 16:31
@Gibbio ive listed a bunch of ocsp servers including the ones shipped with firefox by default at #73 
pretty sure 2 of the requests you got after disabling addons etc were ocsp requests (the google ip is very close to, and acts exactly like a google ocsp server i encountered). they are nothing to worry about

however, for firefox to be making ocsp requests in the first place, i think it means some ssl requests were made to some sites first. it can be all sorts of things. this user.js doesnt disable all background requests by default. also even if you disable your addons, they can still be checked for updates. maybe go through user.js and/or about:config and look for anything with urls or any enabled features which contact urls to investigate. worst case scenario its something user.js missed out but i doubt it since you're using an older version of firefox

**Comment by CHEF-KOCH** [comment] 2015-11-05 17:08
I don't see any reasons to use a whitelist ip list, due the fact google have over 200k ip's and they might change very fast and often. So if you want better work with the domains only, the problem about your list is that it not respect the CA's because if we strip some away you not need to whitelist it. So it overall not make much sense to use a whitelist in a whielist (since Mozilla already included a whitelist, see [here](https://wiki.mozilla.org/CA:OCSP-TrustedResponder), [here](https://wiki.mozilla.org/NSS:BurnDownList) and [here](https://mxr.mozilla.org/mozilla-central/source/security/certverifier/CNNICHashWhitelist.inc). SO with much respect to your wokr it would be better to report directly suspect certificates/servers to mozilla or google safe-browsing instead of working with a whitelist that comes without benefits.

**Comment by berrythesoftwarecodeprogrammar** [comment] 2015-11-05 17:12
i wasnt suggesting anyone make an ip whitelist, or any whitelist. it was just so that people could know whether or not ips belong to ocsp servers

**Comment by CHEF-KOCH** [comment] 2015-11-05 17:14
They still not know anything, because as I said the ip could be changed or they just create an sub-domain which would ruine your entire list. E.g. if you already whitelisted google.com you not need to whitelist google.com/whatever this is redundant. As I said you can't block them anyway because you get problems, in this case if you block/enable a specific port within firefox or block it while ocsp was enabled you get the warning anyway.

**Comment by berrythesoftwarecodeprogrammar** [comment] 2015-11-05 17:21
i dont expect it to be a timeless list. and theres no talk of blocking or whitelisting! i just did it because i felt like it. people can do whatever they like with it. lol

**Comment by CHEF-KOCH** [comment] 2015-11-05 17:24
Don't get me wrong on this, I like such work and it's not against your list but as I said there isn't any benefit. Maybe if you want to monitor it I could add this to my NoScript project.

**Comment by berrythesoftwarecodeprogrammar** [comment] 2015-11-05 17:25
which noscript project?

**Comment by CHEF-KOCH** [comment] 2015-11-05 17:37
This [one](https://github.com/CHEF-KOCH/NoScript-Whitelist), I will also uMatrix and uBlock too, well it also suffers from my mentioned stuff but it is more designed for users which don't know much about the configurations and it should help in this case. If you want I can give your access and build something like a quick whitelist for several reasons, like to compare or easier set-up specific things in Firefox.

**Comment by berrythesoftwarecodeprogrammar** [comment] 2015-11-05 17:46
sure, do u want to talk somewhere else? we kinda hijacked this issue

**Comment by CHEF-KOCH** [comment] 2015-11-05 17:47
Yes, I always like fresh and new ideas. Maybe we can add an issue report over there and see what we can do to help others and possible create something like a database.

**Comment by pyllyukko** [comment] 2015-11-05 22:04
I noticed from ```about:networking``` that my Firefox is still making connections to both tiles.services.mozilla.com and tiles-cloudfront.cdn.mozilla.net. We might need to configure ```browser.newtabpage.directory.source``` to deal the final blow to this tile nuisance.

**Comment by berrythesoftwarecodeprogrammar** [comment] 2015-11-06 03:34
yeah i have mine set to "" and i dont get those connections

**Comment by pyllyukko** [comment] 2015-11-06 03:38
> yeah i have mine set to "" and i dont get those connections

Thought so. Any idea what's the difference with specifying ```""``` and ```"data:application/json,{}"``` (from <http://forums.mozillazine.org/viewtopic.php?f=7&t=2888321>)?

**Comment by berrythesoftwarecodeprogrammar** [comment] 2015-11-06 04:04
nah no idea. i dont think there'd be any added benefit by doing the latter

**Comment by pyllyukko** [comment] 2015-11-06 13:03
Ping @Gibbio. Can you try again?

**Comment by Atavic** [comment] 2016-10-14 17:31
` user_pref("extensions.webservice.discoverURL", "http://0.0.0.0");`

[Explained...](http://www.wilderssecurity.com/threads/firefox-quiet.375074/#post-2483070)

**Comment by nodiscc** [comment] 2017-03-20 12:34
I think this can be closed. As pointed out above the methodology is flawed. A better approach would be:

 * Setup a packet capture/analysis tool on a gateway machine
 * Ensure all Firefox traffic is forwarded through that machine
 * Ensure no other OS/application network traffic is present
 * Import required certificate in the packet analysis tool, MitM all connections
 * Post decrypted _contents_ and metadata of intercepted traffic here.

This can be done in another issue.

**Closed** 2017-03-20 16:42 UTC
Labels: needs more info

**Comment by Atavic** [comment] 2017-03-20 20:24
That's not a big issue: I mean, it's some `about:config` entry.

```
user_pref("browser.safebrowsing.enabled", true);
user_pref("browser.safebrowsing.malware.enabled", true);
```

These features are set to false in my own hardened user.js as they need some connections to work, as downloading a blacklist of hashes from both mozilla and google.

I also remove every single URL, as:
`user_pref("extensions.blocklist.url", "https://blocklist.addons.mozilla.org/blocklist/`

CNAME of blocklist.addons.mozilla.org is mozaws.net which has various possible IP calls:
https://ipinf.ru/sites-on-ip.php?domain=versioncheck.prod.mozaws.net
