### ISSUE TITLE
Wi-fi infos sending periodically or only when needed? (if geo.enabled = true)

### ISSUE THREAD

**Issue by jackTaw88** [pyllyukko/user.js#440] opened 2019-01-07 21:02 UTC
geo.enabled is of course a privacy issue. But I have a question here:

How geo-location works? If geo.enabled is enabled when Firefox sends periodically user-wifi-data to location server (google or Mozilla) ? Or Firefox sends the user-wifi-data only when web page asks and end-user allow it?

Thank you

**Comment by nodiscc** [comment] 2019-01-08 12:22
After a quick search:

- https://support.mozilla.org/en-US/kb/does-firefox-share-my-location-websites?redirectlocale=en-US&redirectslug=does-firefox-share-my-location-web-sites
- https://security.stackexchange.com/questions/142463/how-effective-is-disabling-firefoxs-geo-enabled-setting-for-increasing-anonymit

> When you visit a location-aware website, Firefox will ask you if you want to share your location. 
> This service is totally optional – Firefox doesn’t share your location without your permission

**Comment by Atavic** [comment] 2019-01-08 18:02
*geo.enabled* is for location-aware websites (maps, etc.) while the location discovery through wi-fi data is another, bigger issue.
An example: https://github.com/ghacksuserjs/ghacks-user.js/issues/152

**Comment by jackTaw88** [comment] 2019-01-09 20:35
If I understand correctly: if I will set geo.enabled=true but I will never accept any web site to get my location there is no privacy issue...
Thank you

**Comment by Atavic** [comment] 2019-01-10 18:05
Yes, but you may find sites that don't ask you anything, as they imply you have read and accepted the EULA.

**Comment by jackTaw88** [comment] 2019-01-10 19:50
@Atavic I'm confused with your last answer. What is going on with EULA ?

**Comment by Atavic** [comment] 2019-01-10 21:52
As [MS](https://github.com/crazy-max/WindowsSpyBlocker/issues/35#issuecomment-292642256) or Google imply, by logging into any of their services, you accept their EULAs. This means they may get your location, eventually.

**Comment by nodiscc** [comment] 2019-01-11 14:49
> you accept their EULAs. This means they may get your location
> location discovery through wi-fi data is another, bigger issue.

This is not related to Firefox. Location disclosure based on IP address or Android leaking data to Google cannot be fixed by a browser. If you're worried about this, use Tor browser/devices without Google software (https://lineageos.org/). `geo.enabled` works as designed. I think this discussion is outside the scope of this project.

**Comment by jackTaw88** [comment] 2019-01-13 08:57
@Atavic Firefox s license (EULA) is MPL. I think it is better for our privacy just because firefox is fully open sourced.

@nodiscc Yes this discussion is out of scope... But I just want to know if my firefox (which is fully open source) send my ip(or any information) if my "geo.enabled=true" even I will not allow (accept) any site to get my location?

I am reading here: https://www.mozilla.org/en-US/privacy/  But I could not get any point about "geo" functionality.

**Comment by nodiscc** [comment] 2019-01-13 13:16
> I just want to know if my firefox send my ip

Well of course your IP address sent on every request, this is how IP networks work... https://en.wikipedia.org/wiki/Computer_network

**Comment by jackTaw88** [comment] 2019-01-16 07:18
> > I just want to know if my firefox send my ip
> 
> Well of course your IP address sent on every request, this is how IP networks work... https://en.wikipedia.org/wiki/Computer_network

@nodiscc yes I know. But the question is:

- firefox sends periodically?
- firefox sends only when a web page asks my location?

**Comment by Thorin-Oakenpants** [comment] 2019-01-16 07:36
> geo.enabled is of course a privacy issue

No it's not. Every single request is behind a prompt (by default). The pref `geo.enabled` controls the API. The default for almost everyone on the planet is this API is accessible. The default for almost everyone on the planet is to prompt (and you can remember the decision and allow exceptions)

Since FF58 you can actually set a default for the prompt: this is the pref `permissions.default.geo` where 0=always ask (default), 1=allow, 2=block . And almost everyone on the planet is default prompt.

If you want to change these, and IF someone wanted to use these two values (even though the site permission one can be an actual site exception), they can be used to build a fingerprint (but why boother, because 99 of the entire world is offering up easier FP'ing info) .. then you stand out, and I mean like 0.00001% of users

see: https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#language .. the last two values

**Comment by Atavic** [comment] 2019-01-16 17:26
@jackTaw88 

> Location data: Firefox uses your IP address to suggest relevant content based on your country.

https://www.mozilla.org/en-US/privacy/firefox/

> If you allow a website to get your location via this service, we will collect, depending on the capabilities of your device, information about the wifi routers closest to you, cell ids of the cell towers closest to you, and the strength of your wifi or cell signal.

https://www.google.com/privacy/lsf.html

^Also see *Information sharing and onward transfer* on bottom.

**Closed** 2019-01-19 12:58 UTC
Labels: question
