### ISSUE TITLE
Addon "Zenmate VPN" broken

### ISSUE THREAD

**Issue by jayphizzle** [pyllyukko/user.js#53] opened 2015-10-08 11:55 UTC
I created a fresh profile, copied the user.js to this profile and installed the zenmate Addon from https://www.zenmate.com. 

After starting vpn connection trough the addon no more website conenction is possible -> "Connection failed". I read that some settings can break addon functions. Do you have a hint what setting cause the issue?

Version: 	42.0b4 (x64) @ Windows 7 Prof. x64
Build-ID: 	20151005144425

Please let me know if you need more informations.

**Comment by CHEF-KOCH** [comment] 2015-10-08 12:59
Sorry no beta versions. The user.js is for final products. Maybe Mozilla changed some stuff again which breaks the addon itself. 

Can you give me the entire log and contact the ZenMate support? 

Thanks.

**Comment by jayphizzle** [comment] 2015-10-08 13:19
Uninstalled Beta and installed final version - same issue.

Where can i find a logfile / create one?

Version 	41.0.1
Build-ID 	20150929144111

**Comment by CHEF-KOCH** [comment] 2015-10-08 13:30
You can contact the ZenMate support they are always very friendly and help you step-by-step. 

https://support.zenmate.com/

**Comment by jayphizzle** [comment] 2015-10-08 13:37
Ok i created a issue report @zenmate.

**Comment by pyllyukko** [comment] 2015-10-09 15:56
You can get some pointers when starting Firefox from terminal. There's usually some errors there that might give some indication on what's happening. Also the [web console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console) might reveal something.

**Comment by jayphizzle** [comment] 2015-10-12 12:51
I'm waiting for feedback from the zenmate support ....

**Comment by CHEF-KOCH** [comment] 2015-10-25 16:37
> Connection failed

Normally this is on every start with a lot of tabs opened, but it will automatically re-connect after some seconds. 

Any news? Because in meantime I tried it and it works here. The only stuff I noticed that even if you use the premium opt-in that from time to time some servers are down, in this case just switch the location and it works again - but that is not our problem. I never heard that any about:config stuff breaks FF internal proxy/vpn support because this is handled internal and not by any switches, maybe only DNS or something but again that is not our problem.

**Comment by jayphizzle** [comment] 2015-10-26 07:44
> Any news?

Not useful. Got the answer from zenmate that they have no resources to look after the user.js settings.

> Because in meantime I tried it and it works here.

Strange, I tested in on two different clients in two different networks.
I will make further investigations if i found some freetime and update this thread.

But you can close this for now.

**Comment by CHEF-KOCH** [comment] 2015-10-26 09:42
The only thing that really affects VPN is this:

* If you use an AV ensure the the certificate is proper installed, also try to exclude the zenmate domain or simple disable the internal ssl scanning feature (becuase most AV's now act like a proxy/gateway because of there own SSL scanning features).
* Do not use pinning 2 (revert back to 1 and try to delete cert8.db, restart FF (it take some time to-rebuild this) and see if that works. 
* Revert all chiper stuff to defaults.

The pinning + dns/chiper thing is the only stuff that affects internet connection/security directly. 

Of course zenmate can't check all our stuff, because it's optional but you can try my mentioned things and report back. If this still not helps this is another user related or system related misconfiguration.

**Comment by pyllyukko** [comment] 2015-10-27 18:01
> But you can close this for now.

Well it's your ticket, so you close if it's not an issue anymore :)

I'm not using ZenMate and as it seemed to be at least somewhat commercial, I'm not even trying. So I'm currently unable to try to reproduce this issue.

**Comment by CHEF-KOCH** [comment] 2015-10-27 18:05
Also after some talk with an buddy he also highly recommend to disable if in usage, Eset Nod32 SSL scanning feature, seems this is somehow broken (in v9). Just another tip. I also can confirm this on other applications too like fb2k and such. 

So I highly think it's still a user/config problem.

**Comment by CHEF-KOCH** [comment] 2015-11-18 18:35
Please try to play with the <code>network.proxy.no_proxies_on</code> option. And delete 127.0.0.1 or both (also localhost). Disable and re.enable zenmate + reload the page. It should work now.

**Comment by CHEF-KOCH** [comment] 2016-01-15 22:07
Already discussed in #55 and I added now [this one](https://github.com/pyllyukko/user.js/issues/100) to talk about possible extensions that got problems.

**Comment by pyllyukko** [comment] 2016-06-29 21:21
> But you can close this for now.

Closing this now.

**Closed by pyllyukko** 2016-06-29 21:21 UTC
Labels: needs more info
